"""added positon to table speakers

Revision ID: 91f83feb7f8d
Revises: 2c719aca2d9e
Create Date: 2025-07-03 17:06:16.101255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f83feb7f8d'
down_revision = '2c719aca2d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('speakers_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('speakers_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('position')

    # ### end Alembic commands ###
