"""nothing

Revision ID: cf9f43600020
Revises: e06128a23d1f
Create Date: 2025-07-04 16:22:33.024134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9f43600020'
down_revision = 'e06128a23d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendees_company_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('attendees_company_size_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('attendees_first_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('attendees_job_title_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('attendees_last_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('attendees_phone_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('attendees_phone_key'), ['phone'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('attendees_last_name_key'), ['last_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('attendees_job_title_key'), ['job_title'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('attendees_first_name_key'), ['first_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('attendees_company_size_key'), ['company_size'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('attendees_company_name_key'), ['company_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
