"""modified speakers table

Revision ID: e06128a23d1f
Revises: 91f83feb7f8d
Create Date: 2025-07-03 19:42:29.646635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06128a23d1f'
down_revision = '91f83feb7f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('speakers_bio_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('speakers_company_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('speakers_speaker_avatar_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('speakers_speaker_avatar_key'), ['speaker_avatar'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('speakers_company_key'), ['company'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('speakers_bio_key'), ['bio'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
